from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
BACKGROUND = ROOT / "assets" / "winter-math-background.png"
OUTPUT = ROOT / "output" / "2026-autumn-math-remake.png"
W, H = 1242, 1660
FONT = r"C:\Windows\Fonts\msyh.ttc"
BOLD = r"C:\Windows\Fonts\msyhbd.ttc"

def f(size, bold=False):
    return ImageFont.truetype(BOLD if bold else FONT, size)

def centered(draw, text, y, font, fill, stroke=0, stroke_fill="#000000"):
    box = draw.textbbox((0, 0), text, font=font, stroke_width=stroke)
    x = (W - (box[2] - box[0])) // 2
    draw.text((x, y), text, font=font, fill=fill, stroke_width=stroke, stroke_fill=stroke_fill)

def tracked_center(draw, text, y, font, fill, spacing=0, stroke=0, stroke_fill="#000000"):
    widths = [draw.textlength(char, font=font) for char in text]
    total = sum(widths) + max(0, len(text) - 1) * spacing
    x = (W - total) / 2
    for char, width in zip(text, widths):
        draw.text((round(x), y), char, font=font, fill=fill, stroke_width=stroke, stroke_fill=stroke_fill)
        x += width + spacing

def pill(draw, text, y, font, fill="#fffaf0", outline="#b88c40"):
    box = draw.textbbox((0, 0), text, font=font)
    tw, th = box[2] - box[0], box[3] - box[1]
    x = (W - tw - 76) // 2
    draw.rounded_rectangle((x, y, x + tw + 76, y + th + 38), 20, fill=fill, outline=outline, width=3)
    draw.text((x + 38, y + 16), text, font=font, fill="#443b2d")

def benefit(draw, text, x, y):
    draw.rounded_rectangle((x, y, x + 556, y + 104), 21, fill="#fffdf7", outline="#ffffff", width=7)
    draw.rounded_rectangle((x + 18, y + 20, x + 85, y + 87), 14, fill="#2dcc45", outline="#0f5620", width=4)
    draw.line((x + 34, y + 53, x + 47, y + 69, x + 72, y + 37), fill="white", width=8, joint="curve")
    draw.text((x + 110, y + 24), text, font=f(47, True), fill="#111111", stroke_width=3, stroke_fill="white")

bg = Image.open(BACKGROUND).convert("RGB").resize((W, H), Image.Resampling.LANCZOS)
canvas = bg.copy()
draw = ImageDraw.Draw(canvas)

# The supplied words are rendered by code, not generated by the image model.
tracked_center(draw, "义务教育教科书", 72, f(40), "#252019", spacing=9)
tracked_center(draw, "SHUXUE", 137, f(76), "#cf8b1b", spacing=11)
tracked_center(draw, "数学", 232, f(162, True), "#111111", spacing=5)
draw.rounded_rectangle((38, 410, 522, 540), 22, fill="#fff4df")
draw.text((59, 423), "2026秋版", font=f(87, True), fill="#15110e")
pill(draw, "四年级｜上册", 456, f(38))
tracked_center(draw, "北师大版四上数学", 555, f(86, True), "#ff991a", spacing=-3, stroke=10, stroke_fill="#16110e")
tracked_center(draw, "全册备课包", 765, f(96, True), "#c2f1ff", spacing=3, stroke=9, stroke_fill="#151515")
benefit(draw, "全册教案", 48, 1380)
benefit(draw, "课件PPT", 638, 1380)
benefit(draw, "配套练习", 48, 1510)
benefit(draw, "课堂笔记", 638, 1510)

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
canvas.save(OUTPUT, quality=95)
print(OUTPUT)
